kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-readiness-liveness
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 3001
    hostPort: 3001
    protocol: TCP
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
- role: worker
