apiVersion: v1
kind: Service
metadata:
  name: demo-readiness-liveness
spec:
  selector:
    app: demo-readiness-liveness
  ports:
    - name: service
      port: 3001
      targetPort: service
    - name: metrics
      port: 9090
      targetPort: metrics
  type: NodePort

